### ISSUE TITLE
Wrong count for contact groups if contacts have been deleted

### ISSUE THREAD

**Issue by xenuser** [Icinga/icingaweb2#2837]
Sort of moved over from https://github.com/Icinga/icinga2/issues/5152:

I noticed multiple occasions of inconsistencies regarding actual config states and the stuff Icingaweb2 shows.

## Expected Behavior
When deleting a contact, it should disappear also from IDODB.
Furthermore Icingaweb2 should show the correct member count.

## Current Behavior
One particular example I can easily documentate:
I have the contact group contact_ group3 with 3 members: user_a, user_b, user_c

They are imported by Director.
I deleted a contact within the file which is imported by Director.
Looking in Icingaweb2, only the two remaining contacts are shown as members of the contact group, which is correct.
BUT: The member count on the left shows "3".

Looking into IDODB, I can see that the recently deleted contact is still there and a member of the service group.

So, Icingaweb2 shows the correct members, but displays the wrong member count from IDODB. See screenshot as a proof. Sorry for the black bars on the screenshot, I had to make sure that no one can read any sensitive data. 

The deleted contact there looks like this:

```
*************************** 2. row ***************************
                   contact_id: 22
                  instance_id: 4
                  config_type: 1
            contact_object_id: 35809
                        alias: user_b
                email_address: user_b@domain.tld
                pager_address:
    host_timeperiod_object_id: 0
 service_timeperiod_object_id: 0
   host_notifications_enabled: 1
service_notifications_enabled: 1
          can_submit_commands: 1
      notify_service_recovery: 1
       notify_service_warning: 1
       notify_service_unknown: 1
      notify_service_critical: 1
      notify_service_flapping: 1
      notify_service_downtime: 1
         notify_host_recovery: 1
             notify_host_down: 1
      notify_host_unreachable: 0
         notify_host_flapping: 1
         notify_host_downtime: 1
                  config_hash: somehash
                   object_id: 35809
                  instance_id: 4
                objecttype_id: 10
                        name1: user_b
                        name2: NULL
                    is_active: 0

```

![auswahl_028](https://cloud.githubusercontent.com/assets/2216868/25797370/3597b7f4-33dd-11e7-9fcd-d720a5f38794.png)

So: It looks like Icingaweb2 counts disabled objects in when displaying the number of group members.

## Steps to Reproduce (for bugs)
I deleted a contact within the file which is imported by Director.

## Context
I saw many other occasions where Icingaweb2 seems to show wrong member counts for groups (contacts, services, hosts).

While it is hard to proove that this happens, I try to describe this issue using the contact group example.

## Your Environment
- SLES 12 SP1
- Icinga2 2.6.1
- icinga2-ido-mysql 2.6.1
- Icingaweb2 2.4.1
- Director: latest version
- Fileshipper: latest version
