### ISSUE TITLE
Header not using full width with 4k screens

### ISSUE THREAD

**Issue by Mikesch-mp** [Icinga/icingaweb2#3374]
On my 4k monitor the header is not using the full width.

![image](https://user-images.githubusercontent.com/6574967/36802901-6ee84b3c-1cb6-11e8-8397-ae2ab6004164.png)

## Expected Behavior
Header uses full width on 4 k monitors

## Current Behavior
Width is capped by css file at 240em

## Possible Solution
Change 
```css
@media screen and (min-width: 240em) {
  #header {
    width: 240em;
  }

  #main {
    width: 227em;
  }
}
```
 
Change  to

```css
@media screen and (min-width: 240em) {
  #header {
    min-width: 240em;
  }

  #main {
    width: 227em;
  }
}
```
But i dont know if it will break other things in the UI.

## Steps to Reproduce (for bugs)
1. Login into Icinga using a 4k monitor

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.5.1
```
batman | master
businessprocess | 2.1.0
ca | 1.0.0
cube | 1.0.1
director | 1.4.3
doc | 2.5.1
fileshipper | 1.0.1
generictts | 2.0.0
globe | 1.0.4
grafana | 1.2.0
lsd | 1.0.1
map | 1.0.3
monitoring | 2.5.1
reporting | 0.0.0
translation | 2.5.1
unicorn | 1.0.2
```

* Version used (`icinga2 --version`): 2.8.1
* Operating System and version: CentOS 7.4
