### ISSUE TITLE
Column with issues with .container { width != 0 }

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2#4042]
Director is one of the modules using a custom column width. It sticks with 50/50 instead of the default 33/66 on wider screens. This works fine up to v2.7.3, but leads to the following result with the current master:

![web2_master-cols](https://user-images.githubusercontent.com/553008/72001056-dcb16680-3244-11ea-8e98-8298f345af9b.png)

To reproduce this go to any host in the monitoring module an click on "Modify".

**Comment by nilmerg** [comment]
This is IMHO to be adjusted in director:

```css
#layout.twocols #col1:not(.icinga-module.module-director) + #layout.twocols .icinga-module.module-director#col2 {
  flex-grow: 1; // Should have the same effect as width:50%
}
```
